[package]
edition = "2021"
name    = "voyager-client-module-ethereum"
version = "0.1.0"

[dependencies]
beacon-api-types = { workspace = true, features = ["serde"] }
chain-utils        = { workspace = true }
enumorph           = { workspace = true }
ethereum-light-client-types = { workspace = true, features = ["proto", "serde"] }
futures            = { workspace = true }
jsonrpsee          = { workspace = true, features = ["macros", "server", "tracing"] }
macros             = { workspace = true }
prost              = { workspace = true }
serde              = { workspace = true, features = ["derive"] }
serde-utils        = { workspace = true }
serde_json         = { workspace = true }
thiserror          = { workspace = true }
tokio              = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
unionlabs          = { workspace = true }
voyager-message    = { workspace = true }
voyager-vm         = { workspace = true }
