[package]
edition = "2021"
name    = "arbitrum-light-client-types"
version = "0.1.0"

[dependencies]
ethereum-light-client-types = { workspace = true }
protos                      = { workspace = true, optional = true, features = ["union+ibc+lightclients+arbitrum+v1"] }
rlp                         = { workspace = true, features = ["derive"] }
serde                       = { workspace = true, optional = true, features = ["derive"] }
sha3                        = { workspace = true }
thiserror                   = { workspace = true }
unionlabs                   = { workspace = true }

[features]
default = ["proto", "serde"]
proto   = ["dep:protos", "unionlabs/proto", "ethereum-light-client-types/proto"]
serde   = ["dep:serde", "ethereum-light-client-types/serde"]

[dev-dependencies]
hex-literal = { workspace = true }
