[package]
edition = "2021"
name    = "ethereum-light-client-types"
version = "0.1.0"

[dependencies]
protos         = { workspace = true, features = ["union+ibc+lightclients+ethereum+v1"] }
serde          = { workspace = true, features = ["derive"] }
thiserror      = { workspace = true }
unionlabs      = { workspace = true }

[features]
default = ["proto"]
proto   = ["unionlabs/proto"]

[dev-dependencies]
hex-literal = { workspace = true }
