[package]
edition = "2021"
name    = "scroll-light-client-types"
version = "0.1.0"

[dependencies]
alloy                       = { workspace = true, features = ["sol-types"], optional = true }
ethereum-light-client-types = { workspace = true }
protos                      = { workspace = true, optional = true, features = ["union+ibc+lightclients+scroll+v1"] }
rlp                         = { workspace = true, features = ["derive"] }
serde                       = { workspace = true, optional = true, features = ["derive"] }
serde-utils                 = { workspace = true }
sha3                        = { workspace = true }
thiserror                   = { workspace = true }
unionlabs                   = { workspace = true }

[features]
default = ["proto"]
proto   = ["dep:protos", "unionlabs/proto"]
serde   = ["dep:serde", "ethereum-light-client-types/serde"]
ethabi  = ["dep:alloy", "ethereum-light-client-types/ethabi", "unionlabs/ethabi"]

[dev-dependencies]
hex-literal = { workspace = true }
