[package]
authors      = ["Union Labs"]
edition      = "2021"
license-file = { workspace = true }
name         = "arbitrum-light-client"
publish      = false
version      = "0.1.0"

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
alloy                       = { workspace = true, features = ["sol-types"] }
arbitrum-light-client-types = { workspace = true, features = ["proto"] }
arbitrum-verifier           = { workspace = true }
cosmwasm-std                = { version = "2.1.4", features = ["abort"] }
ethereum-light-client       = { workspace = true, features = ["library"] }
ethereum-light-client-types = { workspace = true, features = ["serde", "ethabi"] }
evm-storage-verifier        = { workspace = true }
hex                         = { workspace = true }
protos                      = { workspace = true }
rlp                         = { workspace = true }
schemars                    = { workspace = true }
serde                       = { workspace = true, features = ["derive"] }
serde-json-wasm             = { workspace = true }
sha3                        = { workspace = true }
thiserror                   = { workspace = true }
union-ibc-light-client      = { workspace = true }
union-ibc-msg               = { workspace = true }
unionlabs                   = { workspace = true, features = ["ethabi"] }

[dev-dependencies]
base64     = { workspace = true }
hex        = { workspace = true }
serde_json = { workspace = true }

[features]
library = []
