[package]
edition = "2021"
name    = "berachain-light-client-types"
version = "0.1.0"

[dependencies]
beacon-api-types              = { workspace = true }
ethereum-light-client-types   = { workspace = true }
protos                        = { workspace = true, optional = true, features = ["union+ibc+lightclients+berachain+v1"] }
serde                         = { workspace = true, optional = true, features = ["derive"] }
tendermint-light-client-types = { workspace = true }
thiserror                     = { workspace = true }
unionlabs                     = { workspace = true }

[features]
default = ["proto"]
proto = [
  "dep:protos",
  "unionlabs/proto",
  "tendermint-light-client-types/proto",
  "ethereum-light-client-types/proto",
]
serde = ["beacon-api-types/serde", "ethereum-light-client-types/serde", "dep:serde"]
